# Generated by Django 5.2 on 2025-05-06 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_profile_full_name_remove_profile_phone_and_more'),
    ]

    operations = [
    ]
