# Generated by Django 5.2 on 2025-05-17 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_profile_avatar_remove_profile_cards_collected_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='preferred_contact',
        ),
    ]
