# Generated by Django 5.2 on 2025-05-08 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riftwood', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series_id', models.IntegerField(unique=True)),
                ('series_name', models.CharField(max_length=50)),
                ('series_image', models.ImageField(upload_to='series/')),
            ],
        ),
        migrations.RenameField(
            model_name='card',
            old_name='image',
            new_name='card_image',
        ),
    ]
