# Generated by Django 5.2 on 2025-05-19 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riftwood', '0003_customorder_instrument_delete_card_delete_rarity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customorder',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('in_production', 'In Production'), ('quality_check', 'Quality Check'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='instrument',
            name='category',
            field=models.CharField(choices=[('electric_guitar', 'Custom Electric Guitar'), ('bass', 'Custom Bass Guitar'), ('drums', 'Custom Drums')], max_length=20),
        ),
    ]
