# Generated by Django 5.2 on 2025-05-19 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riftwood', '0004_alter_customorder_status_alter_instrument_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='customorder',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
