# Generated by Django 5.2 on 2025-05-19 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riftwood', '0005_customorder_total_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customorder',
            name='instrument',
            field=models.CharField(choices=[('electric_guitar', 'Custom Electric Guitar'), ('bass', 'Custom Bass Guitar'), ('drums', 'Custom Drum Kit')], max_length=20),
        ),
        migrations.RemoveField(
            model_name='customorder',
            name='total_price',
        ),
        migrations.DeleteModel(
            name='Instrument',
        ),
    ]
