# Generated by Django 5.2 on 2025-05-27 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riftwood', '0006_alter_customorder_instrument_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customorder',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
